// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB750lB0_NOZbgeJlq1hxyAx9m13O0U1RA',
    appId: '1:136916103479:android:ac9821ccba43254fd2aab2',
    messagingSenderId: '136916103479',
    projectId: 'notification-mob',
    storageBucket: 'notification-mob.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZJF6JqpO0kTiL6Pg94Ldnvc8GqRKRdhU',
    appId: '1:136916103479:ios:f3be00a40748e4b2d2aab2',
    messagingSenderId: '136916103479',
    projectId: 'notification-mob',
    storageBucket: 'notification-mob.appspot.com',
    iosClientId: '136916103479-j0vm9nofvdkbfopv8qs2j3jsa5vo440q.apps.googleusercontent.com',
    iosBundleId: 'com.nikita.notification',
  );
}
